#!/bin/bash
# get array LETSENCRYPT_CONTAINERS

unset LETSENCRYPT_CONTAINERS
source /app/letsencrypt_service_enabled_domain

# remove containerid (cid) to LETSENCRYPT_CONTAINERS
LETSENCRYPT_CONTAINERS=($(printf "%s\n" "${LETSENCRYPT_CONTAINERS[@]}" | sort -u ))

echo ${LETSENCRYPT_CONTAINERS[@]}
LETSENCRYPT_CONTAINERS=(${LETSENCRYPT_CONTAINERS[@]/$1})
cat > /app/letsencrypt_service_enabled_domain <<EOL
LETSENCRYPT_CONTAINERS=(${LETSENCRYPT_CONTAINERS[@]})
EOL
#remove domain folder
rm -f /etc/nginx/certs/$2.{crt,key,dhparam.pem}


source /app/letsencrypt_service --source-only

update_certs --force-reload-nginx

